name: light_games
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.2
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  google_fonts:
  lottie:
  flutter_svg:
  flutter_animate:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:

  uses-material-design: true

  assets:
    - lib/data/liar_game_words.json
    - lib/data/charades_words.json